export const navigation = [
  {
    title: 'Introduction',
    links: [
      { title: 'How to read this site', href: '/' },
      { title: 'Components catalog', href: '/docs/components-catalog' },
    ],
  },
  {
    title: 'Subsystems',
    href: '/docs/subsystems',
    links: [
      { title: 'Dispatch daemon', href: '/docs/subsystems/dispatch-daemon' },
      { title: 'Scheduler', href: '/docs/subsystems/scheduler' },
      { title: 'WebSocket streams', href: '/docs/subsystems/websocket-streams' },
      { title: 'Horizon queues', href: '/docs/subsystems/horizon-queues' },
      { title: 'Market regime', href: '/docs/subsystems/market-regime' },
      { title: 'Notifications', href: '/docs/subsystems/notifications' },
    ],
  },
  {
    title: 'Servers',
    href: '/docs/servers',
    links: [
      { title: 'Architecture overview', href: '/docs/servers/architecture-overview' },
      { title: 'Kraite (all-in-one production)', href: '/docs/servers/kraite' },
    ],
  },
  {
    title: 'Business domains',
    href: '/docs/domains',
    links: [
      { title: 'Open positions', href: '/docs/domains/open-positions' },
      { title: 'Orders', href: '/docs/domains/orders' },
      { title: 'Accounts', href: '/docs/domains/accounts' },
      { title: 'Indicators', href: '/docs/domains/indicators' },
      { title: 'Token selection', href: '/docs/domains/token-selection' },
    ],
  },
  {
    title: 'Lifecycles',
    href: '/docs/lifecycles',
    links: [
      { title: 'Position lifecycle', href: '/docs/lifecycles/position-lifecycle' },
      { title: 'Signal → direction', href: '/docs/lifecycles/signal-direction' },
      { title: 'Order lifecycle', href: '/docs/lifecycles/order-lifecycle' },
    ],
  },
  {
    title: 'Dynamic Commands',
    href: '/docs/dynamic-commands',
    links: [
      { title: 'Kraite — commit', href: '/docs/dynamic-commands/kraite-commit' },
      { title: 'Kraite — deploy', href: '/docs/dynamic-commands/kraite-deploy' },
      { title: 'Kraite — health', href: '/docs/dynamic-commands/kraite-health' },
      { title: 'Kraite — profile', href: '/docs/dynamic-commands/kraite-profile' },
      { title: 'Kraite — push', href: '/docs/dynamic-commands/kraite-push' },
      { title: 'Kraite — read-docs', href: '/docs/dynamic-commands/kraite-read-docs' },
      { title: 'Kraite — reboot', href: '/docs/dynamic-commands/kraite-reboot' },
      { title: 'Kraite — release', href: '/docs/dynamic-commands/kraite-release' },
      { title: 'Kraite — server-upgrade', href: '/docs/dynamic-commands/kraite-server-upgrade' },
      { title: 'Kraite — tag', href: '/docs/dynamic-commands/kraite-tag' },
      { title: 'Kraite — update-docs', href: '/docs/dynamic-commands/kraite-update-docs' },
      { title: 'Kraite — warmup', href: '/docs/dynamic-commands/kraite-warmup' },
      { title: 'Quanamo — deploy', href: '/docs/dynamic-commands/quanamo-deploy' },
      { title: 'Quanamo — health', href: '/docs/dynamic-commands/quanamo-health' },
      { title: 'Quanamo — read-docs', href: '/docs/dynamic-commands/quanamo-read-docs' },
      { title: 'Quanamo — release', href: '/docs/dynamic-commands/quanamo-release' },
      { title: 'Quanamo — tag', href: '/docs/dynamic-commands/quanamo-tag' },
      { title: 'Quanamo — update-docs', href: '/docs/dynamic-commands/quanamo-update-docs' },
      { title: 'Quanamo — warmup', href: '/docs/dynamic-commands/quanamo-warmup' },
      { title: 'Ralph — archive', href: '/docs/dynamic-commands/ralph-archive' },
      { title: 'Ralph — clean', href: '/docs/dynamic-commands/ralph-clean' },
      { title: 'Ralph — convert', href: '/docs/dynamic-commands/ralph-convert' },
      { title: 'Ralph — deploy', href: '/docs/dynamic-commands/ralph-deploy' },
      { title: 'Ralph — install', href: '/docs/dynamic-commands/ralph-install' },
      { title: 'Ralph — monitor', href: '/docs/dynamic-commands/ralph-monitor' },
      { title: 'Ralph — post-review', href: '/docs/dynamic-commands/ralph-post-review' },
      { title: 'Ralph — prepare', href: '/docs/dynamic-commands/ralph-prepare' },
      { title: 'Ralph — task', href: '/docs/dynamic-commands/ralph-task' },
      { title: 'brainstorm', href: '/docs/dynamic-commands/brainstorm' },
      { title: 'code-review', href: '/docs/dynamic-commands/code-review' },
      { title: 'code-safe', href: '/docs/dynamic-commands/code-safe' },
      { title: 'commit', href: '/docs/dynamic-commands/commit' },
      { title: 'confirm', href: '/docs/dynamic-commands/confirm' },
      { title: 'cv', href: '/docs/dynamic-commands/cv' },
      { title: 'distill', href: '/docs/dynamic-commands/distill' },
      { title: 'elicitate', href: '/docs/dynamic-commands/elicitate' },
      { title: 'explain', href: '/docs/dynamic-commands/explain' },
      { title: 'fix', href: '/docs/dynamic-commands/fix' },
      { title: 'forget', href: '/docs/dynamic-commands/forget' },
      { title: 'learn', href: '/docs/dynamic-commands/learn' },
      { title: 'memorize', href: '/docs/dynamic-commands/memorize' },
      { title: 'memory', href: '/docs/dynamic-commands/memory' },
      { title: 'pest', href: '/docs/dynamic-commands/pest' },
      { title: 'prd', href: '/docs/dynamic-commands/prd' },
      { title: 'pull', href: '/docs/dynamic-commands/pull' },
      { title: 'push', href: '/docs/dynamic-commands/push' },
      { title: 'read-docs', href: '/docs/dynamic-commands/read-docs' },
      { title: 'refactor', href: '/docs/dynamic-commands/refactor' },
      { title: 'screenshot', href: '/docs/dynamic-commands/screenshot' },
      { title: 'tag', href: '/docs/dynamic-commands/tag' },
      { title: 'tm', href: '/docs/dynamic-commands/tm' },
      { title: 'troubleshoot', href: '/docs/dynamic-commands/troubleshoot' },
      { title: 'update-docs', href: '/docs/dynamic-commands/update-docs' },
      { title: 'upset', href: '/docs/dynamic-commands/upset' },
      { title: 'xss-audit', href: '/docs/dynamic-commands/xss-audit' },
    ],
  },
]
